import {createServerFn} from '@tanstack/react-start';import {requireSupabaseAuth} from '@/integrations/supabase/auth-middleware';import {z} from 'zod';
export const getAdminData=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{const {data:role}=await context.supabase.from('user_roles').select('role').eq('user_id',context.userId).eq('role','admin').maybeSingle();if(!role)throw new Error('Owner access required');const [products,orders,categories,brands]=await Promise.all([context.supabase.from('products').select('*,product_sizes(*)'),context.supabase.from('orders').select('*,order_items(*)').order('created_at',{ascending:false}),context.supabase.from('categories').select('*'),context.supabase.from('brands').select('*')]);if(products.error||orders.error)throw new Error('Unable to load store management');return {products:products.data??[],orders:orders.data??[],categories:categories.data??[],brands:brands.data??[]}});
const productSchema=z.object({id:z.string().uuid().optional(),name:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/),brand:z.string().min(1),category:z.string().min(1),price:z.number().int().min(0),sale_price:z.number().int().min(0).nullable(),size_type:z.enum(['clothing','footwear','kids_clothing','kids_footwear','none']),image_key:z.string(),images:z.array(z.string().url()),colors:z.array(z.string()).min(1),description:z.string(),league:z.string().nullable(),sizes:z.array(z.object({size:z.string(),stock:z.number().int().min(0)})).min(1)});
export const saveProduct=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(productSchema).handler(async({data,context})=>{const {data:role}=await context.supabase.from('user_roles').select('role').eq('user_id',context.userId).eq('role','admin').maybeSingle();if(!role)throw new Error('Owner access required');const {sizes,...p}=data;const {data:saved,error}=await context.supabase.from('products').upsert({...p,images:p.images}).select('id').single();if(error||!saved)throw new Error('Unable to save product');const {error:sizeError}=await context.supabase.from('product_sizes').upsert(sizes.map(s=>({...s,product_id:saved.id})));if(sizeError)throw new Error('Unable to save size stock');return true});
export const archiveProduct=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(z.object({id:z.string().uuid()})).handler(async({data,context})=>{const {error}=await context.supabase.from('products').update({active:false}).eq('id',data.id).select('id').single();if(error)throw new Error('Owner access required');return true});
export const updateOrderStatus=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(z.object({id:z.string().uuid(),status:z.enum(['Pending','Paid','Shipped','Delivered','Cancelled'])})).handler(async({data,context})=>{const {error}=await context.supabase.from('orders').update({status:data.status}).eq('id',data.id).select('id').single();if(error)throw new Error('Owner access required');return true});
export const saveTaxonomy=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(z.object({type:z.enum(['categories','brands']),slug:z.string().regex(/^[a-z0-9-]+$/),name:z.string().min(2)})).handler(async({data,context})=>{const {error}=await context.supabase.from(data.type).upsert({slug:data.slug,name:data.name}).select('slug').single();if(error)throw new Error('Owner access required');return true});
export const getAccount=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{const [profile,orders]=await Promise.all([context.supabase.from('profiles').select('*').eq('id',context.userId).single(),context.supabase.from('orders').select('order_number,status,total,order_items(name,size,quantity)').eq('user_id',context.userId)]);return {profile:profile.data,orders:orders.data??[]}});
export const saveProfile=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(z.object({full_name:z.string().min(2).max(100),addresses:z.array(z.object({street:z.string(),city:z.string(),state:z.string()}))})).handler(async({data,context})=>{const {error}=await context.supabase.from('profiles').update(data).eq('id',context.userId);if(error)throw new Error('Unable to save profile');return true});
