import { createServerFn } from '@tanstack/react-start';
import { createClient } from '@supabase/supabase-js';
import { getRequestHeader } from '@tanstack/react-start/server';
import { z } from 'zod';
import type { Database } from '@/integrations/supabase/types';

export const getCatalog = createServerFn({method:'GET'}).handler(async()=>{
 const db=createClient<Database>(process.env['SUPABASE_URL']!,process.env['SUPABASE_PUBLISHABLE_KEY']!,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{apikey:process.env['SUPABASE_PUBLISHABLE_KEY']!}},accessToken:async()=>null});
 const {data,error}=await db.from('products').select('*,product_sizes(*)').eq('active',true).order('created_at',{ascending:false}); if(error) throw new Error('The collection could not be loaded. Please try again.');return data;
});
const tokenSchema=z.string().uuid();
const itemSchema=z.object({product_id:z.string().uuid(),size:z.string().min(1).max(20),color:z.string().min(1).max(30),quantity:z.number().int().min(1).max(20)});
export type CartItem=z.infer<typeof itemSchema>;
async function hashToken(token:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));return Array.from(new Uint8Array(bytes)).map(v=>v.toString(16).padStart(2,'0')).join('');}
export const readCart=createServerFn({method:'POST'}).validator(z.object({token:tokenSchema})).handler(async({data})=>{const {supabaseAdmin}=await import('@/integrations/supabase/client.server');const {data:cart,error}=await supabaseAdmin.from('carts').select('items').eq('token_hash',await hashToken(data.token)).maybeSingle();if(error)throw new Error('Unable to open your bag');return (cart?.items??[]) as CartItem[];});
export const writeCart=createServerFn({method:'POST'}).validator(z.object({token:tokenSchema,items:z.array(itemSchema).max(50)})).handler(async({data})=>{const {supabaseAdmin}=await import('@/integrations/supabase/client.server');for(const item of data.items){const {data:size}=await supabaseAdmin.from('product_sizes').select('stock').eq('product_id',item.product_id).eq('size',item.size).maybeSingle();if(!size||size.stock<item.quantity)throw new Error('This size no longer has enough stock.');}const {error}=await supabaseAdmin.from('carts').upsert({token_hash:await hashToken(data.token),items:data.items,updated_at:new Date().toISOString()});if(error)throw new Error('Unable to save your bag');return true;});
export const placePickupOrder=createServerFn({method:'POST'}).validator(z.object({token:tokenSchema,email:z.string().email(),name:z.string().min(2).max(100),phone:z.string().regex(/^[+\d\s-]{7,20}$/),address:z.object({street:z.string().max(300),state:z.string().max(40),city:z.string().max(100)})})).handler(async({data})=>{const {supabaseAdmin}=await import('@/integrations/supabase/client.server');const {data:order,error}=await supabaseAdmin.rpc('place_pickup_order',{p_hash:await hashToken(data.token),p_email:data.email,p_name:data.name,p_phone:data.phone,p_address:data.address});if(error)throw new Error(error.message);const bearer=getRequestHeader('authorization')?.replace(/^Bearer /,'');if(bearer){const {data:identity}=await supabaseAdmin.auth.getUser(bearer);if(identity.user&&order&&typeof order==='object'&&!Array.isArray(order)&&'id' in order){await supabaseAdmin.from('orders').update({user_id:identity.user.id}).eq('id',String(order['id']));}}return order as {id:string;order_number:string;total:number};});
export const getGuestOrder=createServerFn({method:'POST'}).validator(z.object({token:tokenSchema,id:z.string().uuid()})).handler(async({data})=>{const {supabaseAdmin}=await import('@/integrations/supabase/client.server');const {data:order,error}=await supabaseAdmin.from('orders').select('order_number,total,status,delivery_method,order_items(name,size,color,quantity,unit_price)').eq('id',data.id).eq('token_hash',await hashToken(data.token)).maybeSingle();if(error)throw new Error('Unable to load order');return order;});
export const sendContact=createServerFn({method:'POST'}).validator(z.object({name:z.string().min(2).max(100),email:z.string().email(),message:z.string().min(10).max(2000),website:z.string().max(100).optional()})).handler(async({data})=>{if(data.website)return true;const {supabaseAdmin}=await import('@/integrations/supabase/client.server');const {error}=await supabaseAdmin.from('contact_messages').insert({name:data.name,email:data.email,message:data.message});if(error)throw new Error('Unable to send your message');return true;});
