import { useEffect,useRef,useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight,ChevronLeft,ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { leagues } from '@/lib/catalog';
import premier from '@/assets/premier.webp';import premierMobile from '@/assets/premier-mobile.webp';
import laliga from '@/assets/laliga.webp';import laligaMobile from '@/assets/laliga-mobile.webp';
import bundesliga from '@/assets/bundesliga.webp';import bundesligaMobile from '@/assets/bundesliga-mobile.webp';
import seriea from '@/assets/seriea.webp';import serieaMobile from '@/assets/seriea-mobile.webp';
const slides=[{league:'Premier League',title:'PREMIER LEAGUE',sub:'SEASON KITS.',image:premier,mobile:premierMobile,copy:'Wear your colours. Own the game.'},{league:'La Liga',title:'LA LIGA',sub:'PLAY WITH PASSION.',image:laliga,mobile:laligaMobile,copy:'From the stands to the streets. Make it yours.'},{league:'Bundesliga',title:'BUNDESLIGA',sub:'BUILT FOR THE GAME.',image:bundesliga,mobile:bundesligaMobile,copy:'Big moments. Bold colours. Your club.'},{league:'Serie A',title:'SERIE A',sub:'STYLE MEETS SPORT.',image:seriea,mobile:serieaMobile,copy:'Italian football. Unmistakable style.'}];
export function HeroSlider(){const [current,setCurrent]=useState(0),[hovered,setHovered]=useState(false),[focused,setFocused]=useState(false),[touching,setTouching]=useState(false),[visited,setVisited]=useState([0]),[reduced,setReduced]=useState(false);const touch=useRef({x:0,y:0});const resume=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const paused=hovered||focused||touching;
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setReduced(media.matches);const change=()=>setReduced(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
 const change=(value:number)=>{const next=(value+4)%4;setCurrent(next);setVisited(old=>old.includes(next)?old:[...old,next]);};
 useEffect(()=>{const id=setTimeout(()=>{const next=(current+1)%4;setVisited(old=>old.includes(next)?old:[...old,next])},1000);return()=>clearTimeout(id)},[current]);
 useEffect(()=>()=>clearTimeout(resume.current),[]);
 const finishTouch=()=>{clearTimeout(resume.current);resume.current=setTimeout(()=>setTouching(false),5000)};
 useEffect(()=>{if(paused||reduced)return;const id=setInterval(()=>change(current+1),5000);return()=>clearInterval(id)},[current,paused,reduced]);
 return <><section className="hero-slider" aria-roledescription="carousel" aria-label="League collections" onMouseEnter={()=>setHovered(true)} onMouseLeave={()=>setHovered(false)} onFocusCapture={()=>setFocused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocused(false)}} onTouchStart={e=>{const first=e.touches[0];touch.current={x:first?.clientX??0,y:first?.clientY??0};clearTimeout(resume.current);setTouching(true)}} onTouchCancel={finishTouch} onTouchEnd={e=>{const last=e.changedTouches[0];const dx=touch.current.x-(last?.clientX??touch.current.x);const dy=touch.current.y-(last?.clientY??touch.current.y);if(Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy))change(current+(dx>0?1:-1));finishTouch()}}>{slides.map((s,i)=><div key={s.league} className={'hero-slide '+(current===i?'is-active':'')} aria-hidden={current!==i}>{visited.includes(i)&&<picture><source media="(max-width: 640px)" srcSet={s.mobile}/><img src={s.image} alt={'Football players in motion — '+s.league} width={1600} height={853} loading={i===0?'eager':'lazy'} fetchPriority={i===0?'high':'low'}/></picture>}<div className="hero-shade"/><div className="hero-copy"><div className="hero-eyebrow"><span/>THE NEW SEASON STARTS HERE</div><h1>{s.title}<br/><span>{s.sub}</span></h1><p>{s.copy}<br/>Your favourite kits. Right here in Lagos.</p><Button asChild variant="hero" size="lg"><Link to="/category/$slug" params={{slug:'jerseys'}} search={{league:s.league}} tabIndex={current===i?0:-1}>Shop Now <ArrowRight/></Link></Button><div className="hero-local">LAGOS ROOTS. GLOBAL GAME.</div></div></div>)}<div className="hero-controls"><div className="flex items-center gap-2">{slides.map((s,i)=><Button key={s.league} variant="ghost" size="icon" aria-label={'Show '+s.league+' slide'} aria-pressed={i===current} onClick={()=>change(i)} className={'slide-dot '+(i===current?'active':'')}><span/></Button>)}<span className="slide-counter">0{current+1} / 04</span></div><div className="hero-arrows"><Button variant="glass" size="icon" aria-label="Previous slide" onClick={()=>change(current-1)}><ChevronLeft/></Button><Button variant="glass" size="icon" aria-label="Next slide" onClick={()=>change(current+1)}><ChevronRight/></Button></div></div></section><div className="league-strip"><span className="league-caption">REP YOUR LEAGUE</span><div className="league-links">{leagues.map(l=><Link key={l} to="/category/$slug" params={{slug:'jerseys'}} search={{league:l}}>{l}<ArrowUpRightSmall/></Link>)}{['Arsenal','Real Madrid','Bayern','Inter','Paris Saint-Germain'].map(club=><Link key={club} to="/category/$slug" params={{slug:'jerseys'}} search={{q:club}}>{club}<ArrowUpRightSmall/></Link>)}</div></div></>;
}
function ArrowUpRightSmall(){return <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M6 18 18 6M6 6h12v12"/></svg>}
